# Streamlit Cloud Secrets Configuration
# This file is for local development only
# For production, set these as environment variables in Streamlit Cloud

[secrets]
# MongoDB Configuration
MONGO_URI = "mongodb+srv://itsabhishekpatel01:Ap1mongodb@cluster0.yhx0d.mongodb.net/?retryWrites=true&w=majority"
DB_NAME = "rag_pdf_qa"
COLLECTION_NAME = "documents"

# Groq API Key
GROQ_API_KEY = "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"
